import { SignInButton, SignOutButton, useUser } from "@clerk/nextjs";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import { LoadingPage, LoadingSpinner } from "~/components/loading";
import { api, type RouterOutputs } from "~/utils/api";

dayjs.extend(relativeTime);

const ProfileImg = ({ imageUrl }: { imageUrl: string }) => (
  // todo: up profile quality (change to .png or sth)
  <Image
    src={imageUrl}
    alt="Profile image"
    width={56}
    height={56}
    className="rounded-full"
    quality={100}
  />
  // <img src={imageUrl} alt="Profile image" className="h-14 w-14 rounded-full" />
);

const CreatePostWizard = () => {
  const { user } = useUser();
  const [input, setInput] = useState("");
  const ctx = api.useContext(); // dont inline this or invalidate() wont work as expected 🤷‍♂️
  const { mutate: createPost, isLoading: isPosting } =
    api.posts.create.useMutation({
      onSuccess: () => {
        setInput("");
        void ctx.posts.invalidate();
      },
    });

  if (!user) return null;

  return (
    <form action="#" className="flex gap-3">
      <ProfileImg imageUrl={user.imageUrl} />
      <input
        type="text"
        placeholder="type some emojis 👀"
        className="bg-transparent px-2 text-2xl outline-none"
        value={input}
        onChange={(e) => setInput(e.target.value)}
      />
      <div className="flex items-center">
        {isPosting ? (
          <LoadingSpinner />
        ) : (
          <button onClick={() => createPost({ content: input })}>Post</button>
        )}
      </div>
    </form>
  );
};

type PostWithAuthor = RouterOutputs["posts"]["getAll"][number];
const PostView = (props: PostWithAuthor) => {
  const { post, author } = props;
  return (
    <div className="flex items-center gap-3 border-b border-slate-400 p-4 ">
      <ProfileImg imageUrl={author.imageUrl} />
      <div className="flex flex-col">
        <div className="whitespace-pre text-slate-300">
          <span>{`@${author.username}  ·  `}</span>
          <span className="font-thin">{dayjs(post.createdAt).fromNow()}</span>
        </div>
        <span className="text-2xl">{post.content}</span>
      </div>
    </div>
  );
};

const Feed = () => {
  const { data, isLoading: postsLoading } = api.posts.getAll.useQuery();

  if (!data) return <div>Something went wrong</div>;
  if (postsLoading) return <LoadingPage />;

  return (
    <div className="">
      {data.map((postWithAuthor) => (
        <PostView {...postWithAuthor} key={postWithAuthor.post.id} />
      ))}
    </div>
  );
};

export default function Home() {
  const { isLoaded: userLoaded, isSignedIn } = useUser();

  // start fetching asap
  api.posts.getAll.useQuery();

  if (!userLoaded) return <div />;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen justify-center">
        <div className="h-full w-full border-x border-slate-400 md:max-w-2xl">
          <div className="h-22 flex items-center justify-between border-b border-slate-400 p-4">
            <CreatePostWizard />
            {isSignedIn ? <SignOutButton /> : <SignInButton />}
          </div>
          <Feed />
        </div>
      </main>
    </>
  );
}
